ALTER TABLE arxiv_record
    ADD COLUMN IF NOT EXISTS data_source VARCHAR(128) NOT NULL DEFAULT 'ARXIV',
    ADD COLUMN IF NOT EXISTS language VARCHAR(128) NOT NULL DEFAULT 'en';

ALTER TABLE arxiv_tracker
    ADD COLUMN IF NOT EXISTS data_source VARCHAR(128) NOT NULL DEFAULT 'ARXIV'
